version: '3'
services:

  mongodb:
    image: mongo
    ports:
    - 27017:27017

  tweet_collector:
    build: tweet_collector/
    volumes:
    - ./tweet_collector/:/app
    depends_on:
    - mongodb
    env_file:
    - .env
    
  etl_job:
    build: etl_job/
    volumes:
    - ./etl_job/:/app2
    depends_on:
    - mongodb  
    - postgresdb  
    
  postgresdb:
    image: postgres
    ports:
    - "5555:5432"
    environment:
    - POSTGRES_USER=rub
    - POSTGRES_PASSWORD=123456
    - POSTGRES_DB=twitter
    
  slack_bot:
    build: slack_bot/
    volumes:
    - ./slack_bot/:/app
    depends_on:
    - postgresdb
  
